name: flutter_native_image
description: A new flutter plugin project.
version: 0.0.4
author: btastic <bkonsem@gmail.com>
homepage: https://github.com/btastic

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=1.0.0 <3.0.0'
  flutter: ">=0.1.0 <2.0.0"
  
flutter:
  plugin:
    androidPackage: com.example.flutternativeimage
    pluginClass: FlutterNativeImagePlugin
